name: Run Script and Push Changes

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use the Python version your script requires

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # Run the script
      - name: Run script
        run: python app.py 

      # Debug secret
      - name: Debug secret
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Token: ${{ secrets.PAT }}"

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update: Fetch latest courses and malagim data"
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
